// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./components/Carousel.vue')['default']
    Clients: typeof import('./components/Clients.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    FeaturesAnimation: typeof import('./components/FeaturesAnimation.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HeroHome: typeof import('./components/HeroHome.vue')['default']
    PageIllustration: typeof import('./components/PageIllustration.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
