// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogList: typeof import('./components/BlogList.vue')['default']
    ClientsList: typeof import('./components/ClientsList.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    FeaturedPosts: typeof import('./components/FeaturedPosts.vue')['default']
    FeaturesAnimation: typeof import('./components/FeaturesAnimation.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HeaderBlog: typeof import('./components/HeaderBlog.vue')['default']
    HeaderHome: typeof import('./components/HeaderHome.vue')['default']
    HeroBlog: typeof import('./components/HeroBlog.vue')['default']
    HeroHome: typeof import('./components/HeroHome.vue')['default']
    IonArrowBackOutline: typeof import('~icons/ion/arrow-back-outline')['default']
    IonArrowForwardOutline: typeof import('~icons/ion/arrow-forward-outline')['default']
    PageIllustration: typeof import('./components/PageIllustration.vue')['default']
    Paginate: typeof import('./components/Paginate.vue')['default']
    Plum: typeof import('./components/plum.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    ProjectsList: typeof import('./components/ProjectsList.vue')['default']
    RelatedPosts: typeof import('./components/RelatedPosts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('./components/Tag.vue')['default']
    Typewriter: typeof import('./components/Typewriter.vue')['default']
    Whatsapp: typeof import('./components/Whatsapp.vue')['default']
  }
}

export {}
